artina_apps/artina/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import artists.urls
import download.urls
import feedback.urls
import galleries.urls
import homepage.urls
import paintings.urls
import users.urls

urlpatterns = [
    django.urls.path('', django.urls.include(homepage.urls)),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('artists/', django.urls.include(artists.urls)),
    django.urls.path('download/', django.urls.include(download.urls)),
    django.urls.path('feedback/', django.urls.include(feedback.urls)),
    django.urls.path('galleries/', django.urls.include(galleries.urls)),
    django.urls.path('paintings/', django.urls.include(paintings.urls)),
    django.urls.path('users/', django.urls.include(users.urls)),
    django.urls.path('users/', django.urls.include(django.contrib.auth.urls)),
]

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include(debug_toolbar.urls)
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

artina_apps/artists/urls.py
import django.urls

import artists.views

app_name = 'artists'
urlpatterns = [
    django.urls.path('', artists.views.ArtistsView.as_view(), name='artists'),
    django.urls.path(
        '<slug:slug>/',
        artists.views.ArtistView.as_view(),
        name='artist',
    ),
    django.urls.path(
        'paintings/<slug:slug>/',
        artists.views.ArtistPaintingsView.as_view(),
        name='artist_painting',
    ),
]

artina_apps/download/urls.py
import django.urls

import download.views

app_name = 'download'

urlpatterns = [
    django.urls.path(
        '<path:download_path>',
        download.views.DownloadView.as_view(),
        name='image',
    )
]

artina_apps/galleries/urls.py
import django.urls

import galleries.views

app_name = 'galleries'
urlpatterns = [
    django.urls.path(
        '', galleries.views.GalleriesView.as_view(), name='galleries'
    ),
    django.urls.path(
        '<slug:slug>/',
        galleries.views.GalleryView.as_view(),
        name='gallery',
    ),
    django.urls.path(
        'paintings/<slug:slug>/',
        galleries.views.GalleryPaintingsView.as_view(),
        name='gallery_paintings',
    ),
]

artina_apps/paintings/urls.py
import django.urls

import paintings.views


app_name = 'paintings'
urlpatterns = [
    django.urls.path(
        '<slug:slug>/',
        paintings.views.PaintingView.as_view(),
        name='painting',
    ),
]

artina_apps/users/urls.py
import django.contrib.auth.views
import django.urls

import users.views

app_name = 'users'
urlpatterns = [
    django.urls.path(
        'login/',
        django.contrib.auth.views.LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
    ),
    django.urls.path(
        'sign_up/', users.views.SignUpView.as_view(), name='sign_up'
    ),
    django.urls.path(
        'password_change/done/',
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    django.urls.path(
        'password_change/',
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=django.urls.reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_reset/',
        users.views.PasswordReset.as_view(),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    django.urls.re_path(
        r'password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=django.urls.reverse_lazy(
                'users:password_reset_complete'
            ),
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'password_reset/complete/',
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
    django.urls.path(
        'profile/', users.views.ProfileView.as_view(), name='profile'
    ),
]

artina_apps/paintings/models.py
import datetime

import django.core.validators
import django.db.models
import django.template.defaultfilters
import django.utils.safestring
import sorl.thumbnail

import artists.models
import galleries.models
import users.models


class PaintingManager(django.db.models.Manager):
    def get_filter_paintings(self):
        return (
            self.get_queryset()
            .only(
                Painting.painting_name.field.name,
                Painting.painting_height.field.name,
                Painting.painting_width.field.name,
                Painting.painting_photo.field.name,
                Painting.painting_creation_year.field.name,
                Painting.slug.field.name,
            )
            .order_by(Painting.painting_name.field.name)
        )

    def get_painting(self):
        return (
            self.get_queryset()
            .select_related(
                Painting.painting_artist.field.name,
                Painting.painting_gallery.field.name,
            )
            .prefetch_related(
                django.db.models.Prefetch(
                    Painting.likes.field.name,
                    queryset=users.models.CustomUser.objects.all(),
                    to_attr='painting_likes',
                ),
                django.db.models.Prefetch(
                    PaintingFacts.painting.field.related_query_name(),
                    queryset=PaintingFacts.objects.all(),
                ),
            )
            .only(
                Painting.painting_name.field.name,
                Painting.painting_creation_year.field.name,
                Painting.painting_materials.field.name,
                Painting.painting_width.field.name,
                Painting.painting_height.field.name,
                Painting.slug.field.name,
                # Painting.painting_description.field.name,
                Painting.painting_photo.field.name,
                f'{Painting.painting_artist.field.name}__'
                f'{artists.models.Artists.name.field.name}',
                f'{Painting.painting_artist.field.name}__'
                f'{artists.models.Artists.surname.field.name}',
                f'{Painting.painting_artist.field.name}__'
                f'{artists.models.Artists.patronymic.field.name}',
                f'{Painting.painting_gallery.field.name}__'
                f'{galleries.models.Galleries.gallery_name.field.name}',
            )
        )


class Painting(django.db.models.Model):
    objects = PaintingManager()

    painting_name = django.db.models.CharField(
        'название картины', max_length=50, help_text='Максимум 50 символов'
    )
    painting_artist = django.db.models.ForeignKey(
        artists.models.Artists,
        on_delete=django.db.models.CASCADE,
        related_name='artists',
        verbose_name='художник',
    )
    painting_gallery = django.db.models.ForeignKey(
        galleries.models.Galleries,
        on_delete=django.db.models.CASCADE,
        related_name='galleries',
        verbose_name='галерея',
    )
    painting_creation_year = django.db.models.IntegerField(
        'год создания картины',
        help_text='Введите реальный год создания картины',
        validators=[
            django.core.validators.MinValueValidator(800),
            django.core.validators.MaxValueValidator(
                datetime.date.today().year
            ),
        ],
    )
    painting_width = django.db.models.FloatField(
        'ширина картины',
        help_text='Введите ширину картины',
        validators=[
            django.core.validators.MinValueValidator(10),
            django.core.validators.MaxValueValidator(10000),
        ],
    )
    painting_height = django.db.models.FloatField(
        'высота картины',
        help_text='Введите высоту картины',
        validators=[
            django.core.validators.MinValueValidator(10),
            django.core.validators.MaxValueValidator(10000),
        ],
    )
    painting_materials = django.db.models.CharField(
        'материалы картины',
        max_length=25,
        help_text='Введите материала, которые использовались при создании '
        'картины',
    )
    # painting_description = django.db.models.TextField(
    #     'описание картины',
    #     max_length=1000,
    #     help_text='Напишите описание к картине',
    # )
    painting_photo = django.db.models.ImageField(
        'путь до изображения картины',
        help_text='Введите путь до изображения картины',
        upload_to='picture/',
    )
    slug = django.db.models.SlugField(
        'слаг картины',
        max_length=55,
        help_text='Введите url адрес для картины',
        unique=True,
    )
    likes = django.db.models.ManyToManyField(
        users.models.CustomUser, verbose_name='лайк', blank=True
    )

    @property
    def get_painting_size(self):
        if self.painting_height == int(self.painting_height):
            self.painting_height = int(self.painting_height)
        if self.painting_width == int(self.painting_width):
            self.painting_width = int(self.painting_width)
        return f'{self.painting_width}x{self.painting_height}'

    @property
    def get_image(self):
        return sorl.thumbnail.get_thumbnail(
            self.painting_photo, '250x150', quality=51
        )

    def image_tmb(self):
        if self.painting_photo:
            return django.utils.safestring.mark_safe(
                f'<img src={self.get_image.url} />'
            )
        return 'нет изображения'

    image_tmb.short_description = 'изображение картины'
    image_tmb.allow_tags = True

    def __str__(self):
        return self.painting_name

    class Meta:
        verbose_name = 'картина'
        verbose_name_plural = 'картины'


class PaintingFacts(django.db.models.Model):
    title = django.db.models.CharField(
        'заголовок',
        max_length=100,
        help_text='Напишите заголовок карточки факта',
        null=True,
        blank=True,
    )
    painting = django.db.models.ForeignKey(
        Painting,
        verbose_name='факт',
        related_name='painting_facts',
        on_delete=django.db.models.CASCADE,
    )
    fact = django.db.models.TextField(
        'факт о картине',
        max_length=500,
        help_text='Максимум 500 символов',
    )

    class Meta:
        verbose_name = 'факт о картине'
        verbose_name_plural = 'факты о картине'

    def __str__(self):
        return self.fact[:20]

artina_apps/paintings/views.py
import django.db.models
import django.shortcuts
import django.urls
import django.views.generic

import paintings.models


class PaintingView(django.views.generic.DetailView):
    model = paintings.models.Painting
    template_name = 'paintings/painting.html'
    context_object_name = 'painting'
    queryset = model.objects.get_painting()

    def get_object(self):
        return django.shortcuts.get_object_or_404(
            self.queryset, slug=self.kwargs[self.slug_field]
        )

    def post(self, request, **kwargs):
        painting_slug = kwargs[self.slug_field]
        response = django.shortcuts.get_object_or_404(
            self.model.objects.filter(slug=painting_slug)
        )
        if request.user.is_authenticated:
            if request.user in response.likes.all():
                response.likes.remove(request.user)
            else:
                response.likes.add(request.user)
        else:
            return django.shortcuts.redirect(
                django.urls.reverse_lazy('users:login')
            )
        response.save()
        return django.shortcuts.redirect(
            django.urls.reverse_lazy(
                'paintings:painting', kwargs={self.slug_field: painting_slug}
            )
        )

artina_apps/templates/paintings/painting.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Картина
{% endblock %}

{% block add_css_link %}
<link rel="stylesheet" href="{% static 'css/painting_likes.css' %}">
{% endblock add_css_link %}

{% block content %}
  <h1>{{ painting.painting_name }}</h1>
  <h4>Художник: {{ painting.painting_artist }}</h4>
  <h5>Галерея: {{ painting.painting_gallery }}</h5>
  <h6 class="mb-2">размер: {{ painting.get_painting_size }}</h6>
  {% load thumbnail %}
  {% thumbnail painting.painting_photo '550x350' as ph %}
    <img src="{{ ph.url }}"
             width="{{ ph.width }}"
             height="{{ ph.height }}"
             alt="картина">
  {% endthumbnail %}
  <a href="{% url 'download:image' painting.painting_photo %}" class=
  "mx-auto d-block col-lg-2 col-md-3 col-sm-3 col-xs-6 btn text-blue btn-outline-primary mt-2 mb-3">Скачать изображение</a>
  <h6 class="mt-2 mb-2">год создания: {{ painting.painting_creation_year }}</h6>
  <h6 class="mt-2 mb-2">материалы: {{ painting.painting_materials }}</h6>
  <h4>Интересные факты о картине</h4>
  {% if painting.painting_facts %}
    {% for fact in painting.painting_facts.all %}
      <div class="card col-sm-8 mx-auto mt-2 mb-2 rounded">
        {% if fact.title %}
          <div class="card-header bg-secondary">
              <h6 class="card-title">{{ fact.title }}</h6>
          </div>
        {% endif %}
        <div class="card-body">
          <p class="card-text">{{ fact.fact }}</p>
        </div>
      </div>
    {% endfor %}
  {% endif %}

  <h6 class="text-black">
    Количество лайков: {{ painting.likes.count }}
  </h6>
  <div class="d-inline-block">
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="button_painting_like border-0">
        {% if request.user in painting.likes.all %}
          <img class="img_painting_like" src="{% static 'img/like_red.png' %}" alt="Лайк!">
        {% else %}
          <img class="img_painting_like" src="{% static 'img/like.jpg' %}" alt="Лайк!">
        {% endif %}
      </button>
    </form>
  </div>
  <div>
    <a class='btn btn-primary' href="{% url 'artists:artist' painting.painting_artist.slug %}">Биография художника</a>
    <a class='btn btn-primary' href="{% url 'galleries:gallery' painting.painting_gallery.slug %}">Информация о галереи</a>
  </div>
  <div>
    <a class='btn btn-primary mt-2 mb-3'
           href="{% url 'artists:artist_painting' slug=painting.painting_artist.slug %}">
      Назад к картинам
    </a>
  </div>

{% endblock %}

artina_apps/templates/paintings/paintings.html
{% extends 'base.html' %}

{% block title %}
  Картины художника
{% endblock %}

{% block content %}
  <h1>Картины</h1>
  {% for painting in paintings %}
    {% if forloop.counter0|divisibleby:3 %}
      <div class="row">
    {% endif %}
    <div class="col-4">
      <h5 class="mt-3">{{ painting.painting_name }}</h5>
      <p>Размер: {{ painting.get_painting_size }}</p>
      {% load thumbnail %}
      {% thumbnail painting.painting_photo '350x200' crop='center' as photo %}
        <img class='img-fluid' src="{{ photo.url }}"
                     width="{{ photo.width }}"
                     height="{{ photo.height }}"
                     alt="картина художника">
      {% endthumbnail %}
      <p>Год создания: {{ painting.painting_creation_year }}</p>
      <a href="{% url 'paintings:painting' painting.slug %}"
               class="btn btn-primary" role="button">
        Подробнее о картине
      </a>
    </div>
    {% if forloop.counter >= 3 and forloop.counter|divisibleby:3 or forloop.last %}
      </div>
    {% endif %}
  {% endfor %}
  <a href="{{ request.META.HTTP_REFERER }}"
       class="btn btn-primary mt-3" role="button">
    Вернуться назад
  </a>
{% endblock %}