artina_apps/artina/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import artists.urls
import download.urls
import feedback.urls
import galleries.urls
import homepage.urls
import paintings.urls
import users.urls

urlpatterns = [
    django.urls.path('', django.urls.include(homepage.urls)),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('artists/', django.urls.include(artists.urls)),
    django.urls.path('download/', django.urls.include(download.urls)),
    django.urls.path('feedback/', django.urls.include(feedback.urls)),
    django.urls.path('galleries/', django.urls.include(galleries.urls)),
    django.urls.path('paintings/', django.urls.include(paintings.urls)),
    django.urls.path('users/', django.urls.include(users.urls)),
    django.urls.path('users/', django.urls.include(django.contrib.auth.urls)),
]

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include(debug_toolbar.urls)
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

artina_apps/artists/urls.py
import django.urls

import artists.views

app_name = 'artists'
urlpatterns = [
    django.urls.path('', artists.views.ArtistsView.as_view(), name='artists'),
    django.urls.path(
        '<slug:slug>/',
        artists.views.ArtistView.as_view(),
        name='artist',
    ),
    django.urls.path(
        'paintings/<slug:slug>/',
        artists.views.ArtistPaintingsView.as_view(),
        name='artist_painting',
    ),
]

artina_apps/feedback/urls.py
import django.urls

import feedback.views

app_name = 'feedback'
urlpatterns = [
    django.urls.path(
        '', feedback.views.FeedbackView.as_view(), name='feedback'
    )
]

artina_apps/galleries/urls.py
import django.urls

import galleries.views

app_name = 'galleries'
urlpatterns = [
    django.urls.path(
        '', galleries.views.GalleriesView.as_view(), name='galleries'
    ),
    django.urls.path(
        '<slug:slug>/',
        galleries.views.GalleryView.as_view(),
        name='gallery',
    ),
    django.urls.path(
        'paintings/<slug:slug>/',
        galleries.views.GalleryPaintingsView.as_view(),
        name='gallery_paintings',
    ),
]

artina_apps/homepage/urls.py
import django.urls

import homepage.views

app_name = 'homepage'
urlpatterns = [
    django.urls.path('', homepage.views.HomepageView.as_view(), name='home')
]

artina_apps/users/urls.py
import django.contrib.auth.views
import django.urls

import users.views

app_name = 'users'
urlpatterns = [
    django.urls.path(
        'login/',
        django.contrib.auth.views.LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
    ),
    django.urls.path(
        'sign_up/', users.views.SignUpView.as_view(), name='sign_up'
    ),
    django.urls.path(
        'password_change/done/',
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    django.urls.path(
        'password_change/',
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=django.urls.reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_reset/',
        users.views.PasswordReset.as_view(),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    django.urls.re_path(
        r'password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=django.urls.reverse_lazy(
                'users:password_reset_complete'
            ),
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'password_reset/complete/',
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
    django.urls.path(
        'profile/', users.views.ProfileView.as_view(), name='profile'
    ),
]

artina_apps/templates/includes/footer.html
<footer>
  <div class="container">
  <p class="text-center text-muted">&copy; Made in {% now "Y" %} by TWoWs</p>
  </div>
</footer>

artina_apps/templates/includes/header.html
{% load static %}

<header class="p-2 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <img src={% static 'img/artina.png' %} width="60" height="44" alt="Иконка сайта" class="bi me-2">

      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href='{% url 'homepage:home' %}' class="nav-link px-2
              {% if view_name == 'homepage:home' %}
              text-secondary
              {% else %}
              text-white
              {% endif %}">О нас</a>
          </li>
          <li><a href='{% url 'artists:artists' %}' class="nav-link px-2
              {% if view_name == 'artists:artists' %}
              text-secondary
              {% else %}
              text-white
              {% endif %}">Художники</a>
          </li>
          <li><a href='{% url 'galleries:galleries' %}' class="nav-link px-2
              {% if view_name == 'galleries:galleries' %}
              text-secondary
              {% else %}
              text-white
              {% endif %}">Галереи</a>
          </li>
          <li><a href='{% url 'feedback:feedback' %}' class="nav-link px-2
              {% if view_name == 'feedback:feedback' %}
              text-secondary
              {% else %}
              text-white
              {% endif %}">Обратная связь</a>
          </li>
        </ul>
      {% endwith %}

      {% with request.resolver_match.view_name as view_name %}
        {% if view_name == 'artists:artists' or view_name == 'artists:artist_painting' or view_name == 'galleries:galleries' or view_name == 'galleries:gallery_paintings' %}
          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" method="get">
            {% csrf_token %}
            <input type="search" class="form-control form-control-dark" placeholder="Поиск по странице...">
          </form>
        {% endif %}
      {% endwith %}

      <div class="text-end">
        {% if request.user.is_authenticated %}
          <a href="{% url 'users:profile' %}" role="button" class="btn btn-primary bi me-2">Профиль</a>
          <a href="{% url 'logout' %}" role="button" class="btn btn-primary">Выйти</a>
        {% else %}
          <a href="{% url 'users:login' %}" role="button" class="btn btn-primary bi me-2">Войти</a>
          <a href="{% url 'users:sign_up' %}" role="button" class="btn btn-primary">Регистрация</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>