artina_apps/artina/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import artists.urls
import download.urls
import feedback.urls
import galleries.urls
import homepage.urls
import paintings.urls
import users.urls

urlpatterns = [
    django.urls.path('', django.urls.include(homepage.urls)),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('artists/', django.urls.include(artists.urls)),
    django.urls.path('download/', django.urls.include(download.urls)),
    django.urls.path('feedback/', django.urls.include(feedback.urls)),
    django.urls.path('galleries/', django.urls.include(galleries.urls)),
    django.urls.path('paintings/', django.urls.include(paintings.urls)),
    django.urls.path('users/', django.urls.include(users.urls)),
    django.urls.path('users/', django.urls.include(django.contrib.auth.urls)),
]

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include(debug_toolbar.urls)
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

artina_apps/download/urls.py
import django.urls

import download.views

app_name = 'download'

urlpatterns = [
    django.urls.path(
        '<path:download_path>',
        download.views.DownloadView.as_view(),
        name='image',
    )
]

artina_apps/galleries/urls.py
import django.urls

import galleries.views

app_name = 'galleries'
urlpatterns = [
    django.urls.path(
        '', galleries.views.GalleriesView.as_view(), name='galleries'
    ),
    django.urls.path(
        '<slug:slug>/',
        galleries.views.GalleryView.as_view(),
        name='gallery',
    ),
    django.urls.path(
        'paintings/<slug:slug>/',
        galleries.views.GalleryPaintingsView.as_view(),
        name='gallery_paintings',
    ),
]

artina_apps/users/urls.py
import django.contrib.auth.views
import django.urls

import users.views

app_name = 'users'
urlpatterns = [
    django.urls.path(
        'login/',
        django.contrib.auth.views.LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
    ),
    django.urls.path(
        'sign_up/', users.views.SignUpView.as_view(), name='sign_up'
    ),
    django.urls.path(
        'password_change/done/',
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    django.urls.path(
        'password_change/',
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=django.urls.reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_reset/',
        users.views.PasswordReset.as_view(),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    django.urls.re_path(
        r'password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=django.urls.reverse_lazy(
                'users:password_reset_complete'
            ),
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'password_reset/complete/',
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
    django.urls.path(
        'profile/', users.views.ProfileView.as_view(), name='profile'
    ),
]

artina_apps/galleries/models.py
import django.db.models
import django.template.defaultfilters
import django.utils.safestring
import sorl.thumbnail


class GalleriesManager(django.db.models.Manager):
    def get_gallery_with_photos(self):
        gallery_photos = GalleryPhotos.objects.only(
            GalleryPhotos.photo.field.name,
            GalleryPhotos.gallery_photos_id.field.name,
        )
        gallery_photos_field = GalleryPhotos.gallery_photos
        return self.get_queryset().prefetch_related(
            django.db.models.Prefetch(
                gallery_photos_field.field.related_query_name(),
                queryset=gallery_photos,
            ),
        )

    def get_all_galleries(self):
        return (
            self.get_queryset()
            .all()
            .only(
                Galleries.gallery_name.field.name,
                Galleries.gallery_location.field.name,
                Galleries.gallery_image.field.name,
                Galleries.slug.field.name,
            )
            .order_by(Galleries.gallery_name.field.name)
        )


class Galleries(django.db.models.Model):
    objects = GalleriesManager()

    gallery_name = django.db.models.CharField(
        'название галереи',
        max_length=50,
        help_text='Введите название галереи картин',
        unique=True,
    )
    gallery_location = django.db.models.CharField(
        'расположение галереи',
        max_length=75,
        help_text='Введите локацию галереи',
    )
    slug = django.db.models.SlugField(
        'слаг галереи',
        max_length=55,
        help_text='Введите url адрес для галереи',
        unique=True,
    )
    gallery_description = django.db.models.TextField(
        'описание галереи',
        max_length=1000,
        help_text='Максимум 1000 символов',
    )
    gallery_image = django.db.models.ImageField(
        'путь до изображения галереи',
        upload_to='galleries/',
        help_text='Введите путь до изображения галереи',
    )

    def get_short_description(self):
        return django.template.defaultfilters.truncatechars(
            self.gallery_description, 100
        )

    @property
    def get_image(self):
        return sorl.thumbnail.get_thumbnail(
            self.gallery_image, '200x200', crop='center', quality=51
        )

    def image_tmb(self):
        if self.gallery_image:
            return django.utils.safestring.mark_safe(
                f'<img src={self.get_image.url} /'
            )
        return 'нет изображения'

    image_tmb.short_description = 'фото галереи'
    image_tmb.allow_tags = True

    class Meta:
        verbose_name = 'галерея'
        verbose_name_plural = 'галереи'

    def __str__(self):
        return self.gallery_name


class GalleryPhotos(django.db.models.Model):
    gallery_photos = django.db.models.ForeignKey(
        Galleries,
        related_name='images',
        on_delete=django.db.models.CASCADE,
        verbose_name='фотографии галереи',
    )
    photo = django.db.models.ImageField(
        'путь до фотографии галереи',
        upload_to='galleries/',
        help_text='Выберите путь до фотографии галереи',
    )

    @property
    def get_image(self):
        return sorl.thumbnail.get_thumbnail(
            self.photo, '600x300', crop='center', quality=51
        )

    def image_tmb(self):
        if self.gallery_image:
            return django.utils.safestring.mark_safe(
                f'<img src={self.get_image.url} /'
            )
        return 'нет изображения'

    def __str__(self):
        return self.photo.url

artina_apps/galleries/views.py
import re

import django.db.models
import django.shortcuts
import django.views.generic

import core.views
import galleries.models
import paintings.models


class GalleriesView(django.views.generic.ListView):
    template_name = 'galleries/galleries.html'
    context_object_name = 'galleries'
    queryset = galleries.models.Galleries.objects.get_all_galleries()

    def get_queryset(self):
        result_search = self.request.GET.get('search')
        if result_search:
            text_search = re.escape(result_search)
            self.queryset = (
                self.queryset.filter(gallery_name__iregex=text_search)
                | self.queryset.filter(gallery_description__iregex=text_search)
                | self.queryset.filter(gallery_location__iregex=text_search)
            )
        return self.queryset


class GalleryView(django.views.generic.DetailView):
    model = galleries.models.Galleries
    template_name = 'galleries/gallery.html'
    queryset = model.objects.get_gallery_with_photos()
    context_object_name = 'gallery'

    def get_object(self):
        return self.queryset.get(slug=self.kwargs[self.model.slug.field.name])


class GalleryPaintingsView(django.views.generic.ListView):
    model = galleries.models.Galleries
    template_name = 'paintings/paintings.html'
    context_object_name = 'paintings'

    def get_queryset(self):
        gallery_id = (
            self.model.objects.only(self.model.slug.field.name)
            .get(slug=self.kwargs[self.model.slug.field.name])
            .pk
        )
        painting_objects = paintings.models.Painting.objects
        gallery_paintings = painting_objects.get_filter_paintings().filter(
            painting_gallery=gallery_id
        )
        return core.views.searching_paintings(
            gallery_paintings, self.request.GET.get('search')
        )

artina_apps/templates/galleries/galleries.html
{% extends 'base.html' %}

{% block title %}
  Галереи
{% endblock %}

{% block content %}
  <h1>Галереи</h1>
  {% for gallery in galleries %}
    {% if forloop.counter0|divisibleby:3 %}
      <div class="row">
    {% endif %}
    {% if forloop.counter0 >= 3 and forloop.counter0|divisibleby:3 %}
      </div>
    {% endif %}
    <div class="no-padding col-lg-4 col-md-6 col-sm-12 col-xs-12">
      <h4>{{ gallery.gallery_name }}</h4>
      <p>Расположение: {{ gallery.gallery_location }}</p>
      {% load thumbnail %}
      {% thumbnail gallery.gallery_image '350x200' crop='center' as image %}
        <img class="img-fluid" src="{{ image.url }}"
                     width="{{ image.width }}"
                     height="{{ image.height }}"
                     alt="изображение галереи">
      {% endthumbnail %}
      <div>
        <a href="{% url 'galleries:gallery' gallery.slug %}"
                   class="btn btn-primary mt-2 mb-3 bi me-2" role="button">
          История галереи
        </a>
        <a href="{% url 'galleries:gallery_paintings' slug=gallery.slug %}"
                   class="btn btn-primary mt-2 mb-3" role="button">
          Картины галереи
        </a>
      </div>
    </div>
    {% if forloop.last %}
      </div>
    {% endif %}
  {% endfor %}
{% endblock %}

artina_apps/templates/galleries/gallery.html
{% extends 'base.html' %}

{% block title %}
  Галерея
{% endblock %}

{% load static %}

{% block content %}
  <h1>{{ gallery.gallery_name }}</h1>
  <h5>Местоположение: {{ gallery.gallery_location }}</h5>
  {% load thumbnail %}
  <div class="d-block">
  {% thumbnail gallery.gallery_image '550x350' as ph %}
      <img class='img-fluid' src="{{ ph.url }}"
                 width="{{ ph.width }}"
                 height="{{ ph.height }}"
                 alt="картина">
  {% endthumbnail %}
  </div>
  <a href="{% url 'download:image' gallery.gallery_image %}" class=
  "mx-auto d-block col-lg-2 col-md-3 col-sm-3 col-xs-6 btn text-blue btn-outline-primary mt-2 mb-3">Скачать изображение</a>
  {% if gallery.images %}
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        {% for gallery_image in gallery.images.all %}
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-label="Slide forloop.counter" aria-current="true"></button>
        {% endfor %}
      </div>
      <div class="carousel-inner">
        {% for gallery_image in gallery.images.all %}
          <div class="carousel-item{% if forloop.first %} active{% endif %} text-center">
            <img src="{{ gallery_image.get_image.url }}" />
          </div>
          <div class="container">
            <div class="carousel-caption text-start">
              <p><a href="{% url 'download:image' gallery_image.photo %}" class="
                mx-auto d-block col-lg-2 col-md-3 col-sm-3 col-xs-6 btn text-primary btn-outline-primary mt-2 mb-3">Скачать изображение</a></p>
            </div>
          </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  {% endif %}
  <h4 class="mt-2">История</h4>
  <p class="col-6 mx-auto">{{ gallery.gallery_description }}</p>
  <div>
  <a href="{% url 'galleries:galleries' %}"
           class="btn btn-primary bi me-2 mb-2" role="button">
      К галереям
  </a>
  <a href="{% url 'galleries:gallery_paintings' slug=gallery.slug %}"
           class="btn btn-primary mb-2" role="button">
      Картины галереи
  </a>
  </div>
{% endblock %}