artina_apps/artina/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.auth.urls
import django.urls

import artists.urls
import download.urls
import feedback.urls
import galleries.urls
import homepage.urls
import paintings.urls
import users.urls

urlpatterns = [
    django.urls.path('', django.urls.include(homepage.urls)),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('artists/', django.urls.include(artists.urls)),
    django.urls.path('download/', django.urls.include(download.urls)),
    django.urls.path('feedback/', django.urls.include(feedback.urls)),
    django.urls.path('galleries/', django.urls.include(galleries.urls)),
    django.urls.path('paintings/', django.urls.include(paintings.urls)),
    django.urls.path('users/', django.urls.include(users.urls)),
    django.urls.path('users/', django.urls.include(django.contrib.auth.urls)),
]

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include(debug_toolbar.urls)
        ),
    )
    urlpatterns += django.conf.urls.static.static(
        django.conf.settings.MEDIA_URL,
        document_root=django.conf.settings.MEDIA_ROOT,
    )

artina_apps/homepage/urls.py
import django.urls

import homepage.views

app_name = 'homepage'
urlpatterns = [
    django.urls.path('', homepage.views.HomepageView.as_view(), name='home')
]

artina_apps/users/urls.py
import django.contrib.auth.views
import django.urls

import users.views

app_name = 'users'
urlpatterns = [
    django.urls.path(
        'login/',
        django.contrib.auth.views.LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
    ),
    django.urls.path(
        'sign_up/', users.views.SignUpView.as_view(), name='sign_up'
    ),
    django.urls.path(
        'password_change/done/',
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    django.urls.path(
        'password_change/',
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=django.urls.reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_reset/',
        users.views.PasswordReset.as_view(),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    django.urls.re_path(
        r'password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=django.urls.reverse_lazy(
                'users:password_reset_complete'
            ),
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'password_reset/complete/',
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
    django.urls.path(
        'profile/', users.views.ProfileView.as_view(), name='profile'
    ),
]

artina_apps/users/models.py
import django.contrib.auth.models
import django.db.models

import feedback.models


class CustomUser(django.contrib.auth.models.AbstractUser):
    username = django.db.models.CharField(
        'имя пользователя',
        max_length=30,
        unique=True,
        help_text='Максимальная длина 30 символов',
    )
    email = django.db.models.EmailField(
        'ваша почта',
        unique=True,
    )
    image = django.db.models.ImageField(
        'добавьте картинку профиля',
        upload_to='avatar/%Y/%m/%d',
        blank=True,
    )
    birthday = django.db.models.DateField(
        'дата рождения',
        help_text='Введите свою дату рождения',
        blank=True,
        null=True,
    )
    feedback_mails = django.db.models.ForeignKey(
        feedback.models.Feedback,
        on_delete=django.db.models.CASCADE,
        related_name='feedback',
        verbose_name='письма от пользователя',
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.username


class PasswordResetEmail(django.db.models.Model):
    user_email = django.db.models.EmailField(
        'ваша почта',
    )

    def __str__(self):
        return self.user_email

artina_apps/users/forms.py
import datetime

import django.contrib.auth.forms
import django.core.exceptions
import django.forms

import core.forms
import users.models


class CustomUserCreationForm(
    django.contrib.auth.forms.UserCreationForm, core.forms.BootstrapControlForm
):
    class Meta:
        model = users.models.CustomUser
        fields = (
            users.models.CustomUser.username.field.name,
            users.models.CustomUser.email.field.name,
        )


class CustomUserChangeForm(
    django.contrib.auth.forms.UserChangeForm, core.forms.BootstrapControlForm
):
    class Meta:
        model = users.models.CustomUser
        fields = (
            users.models.CustomUser.username.field.name,
            users.models.CustomUser.email.field.name,
            users.models.CustomUser.first_name.field.name,
            users.models.CustomUser.last_name.field.name,
            users.models.CustomUser.birthday.field.name,
            users.models.CustomUser.image.field.name,
        )
        readonly_fields = ['username']

    def clean(self):
        birthday_field = super().clean().get('birthday', None)
        if birthday_field:
            date = datetime.datetime.today().date()
            if birthday_field >= date:
                self.add_error(
                    users.models.CustomUser.birthday.field.name,
                    'Введите реальную дату рождения',
                )
        return super().clean()


class PasswordResetEmailForm(core.forms.BootstrapControlForm):
    class Meta:
        model = users.models.PasswordResetEmail
        fields = (users.models.PasswordResetEmail.user_email.field.name,)

artina_apps/users/views.py
# import os

import django.contrib
import django.contrib.auth
import django.contrib.auth.mixins
import django.contrib.auth.tokens
import django.contrib.messages
import django.shortcuts
import django.template.loader
import django.urls
import django.utils.encoding
import django.utils.http
import django.views.generic
import dotenv

import core.views
import users.forms
import users.models

dotenv.load_dotenv()


class SignUpView(django.views.generic.CreateView):
    form_class = users.forms.CustomUserCreationForm
    success_url = django.urls.reverse_lazy('users:login')
    template_name = 'users/sign_up.html'

    def form_valid(self, form):
        user = form.save()
        django.contrib.auth.login(self.request, user)
        return super().form_valid(form)


class ProfileView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.FormView,
):
    template_name = 'users/profile.html'
    form_class = users.forms.CustomUserChangeForm
    success_url = django.urls.reverse_lazy('users:profile')

    def get_object(self):
        return self.request.user

    # def form_invalid(self, form):
    #     for error in form.errors:
    #         form.add_error(users.models.CustomUser.username.field.name,
    # error)
    #     return super().form_invalid(form)

    # def form_valid(self, form):
    #     print('8u12p7   yeyo3u2oip1')
    #     old_image = users.models.CustomUser.objects.get(
    #         id=self.request.user.id
    #     ).image
    #     if old_image:
    #         image_path = old_image.path
    #         if os.path.exists(image_path):
    #             os.remove(image_path)
    #     form.save()
    #     return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class(
            initial=self.initial,
            instance=self.request.user,
        )
        return context


class PasswordReset(django.views.generic.FormView):
    template_name = 'users/password_reset.html'
    model = users.models.PasswordResetEmail
    form_class = users.forms.PasswordResetEmailForm

    def form_valid(self, form):
        user_email = form.cleaned_data['user_email']
        try:
            user = users.models.CustomUser.objects.get(email=user_email)
        except users.models.CustomUser.DoesNotExist:
            django.contrib.messages.error(
                self.request,
                'Введите почту, которую вводили при регистрации на сайте.',
            )
            return django.shortcuts.redirect(
                django.urls.reverse_lazy('users:password_reset')
            )
        token = django.contrib.auth.tokens.default_token_generator.make_token(
            user
        )
        msg_data = {
            'user': user.username,
            'protocol': 'http',
            'domain': '127.0.0.1:8000',
            'uid': django.utils.http.urlsafe_base64_encode(
                django.utils.encoding.force_bytes(user.pk)
            ),
            'token': token,
        }
        message = django.template.loader.render_to_string(
            'users/password_reset_mail.html', msg_data
        )
        core.views.send_mail_user(message, user_email, msg_subj='Сброс пароля')
        return django.shortcuts.redirect(
            django.urls.reverse_lazy('users:password_reset_done')
        )

artina_apps/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
  Вход
{% endblock title %}

{% block content %}
  {% if request.user.is_authenticated %}
    <h1 class="mt-2">Вы уже вошли в аккаунт</h1>
  {% else %}
    <h1>Вход</h1>
    {% include 'users/includes/base_users_template.html' %}
  {% endif %}
  <a role="button" class="mt-2 mb-3" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
{% endblock %}

artina_apps/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}
  Смена пароля
{% endblock %}

{% block content %}
  <h1>Смена пароля</h1>
  {% include 'users/includes/base_users_template.html' %}
{% endblock %}

artina_apps/templates/users/password_change_done.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Пароль изменен
{% endblock title %}

{% block content %}
  <h1 class="mb-3">Ваш пароль успешно изменен</h1>
  <p class='col-6 mx-auto'>
    Если вы видите это сообщение, значит ваш пароль был успещно изменен
  </p>
  <a href='{% url 'homepage:home' %}' class="btn btn-primary mb-3" role="button">
    Вернуться на главную
  </a>
{% endblock content %}

artina_apps/templates/users/password_reset.html
{% extends 'base.html' %}


{% block title %}
  Сброс пароля
{% endblock %}

{% block content %}
  <h1>Смена пароля</h1>
  {% if messages %}
    {% for message in messages %}
      <h4 class="alert alert-danger col-6 mx-auto">{{ message }}</h4>
    {% endfor %}
  {% endif %}
  {% include 'users/includes/base_users_template.html' %}
{% endblock %}

artina_apps/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля
{% endblock %}


{% block content %}
  <h1>Пароль успешно изменен</h1>
  <div class="col-6 mx-auto">
    <p>Вы можете войти в свой аккаунт снова, перейдя по кнопке ниже</p>
    <a role="button" href="{% url 'users:login' %}" class="btn btn-primary">
      Войти в аккаунт
    </a>
  </div>
{% endblock %}

artina_apps/templates/users/password_reset_confirm.html
{% extends 'base.html' %}


{% block title %}
  Сброс пароля
{% endblock %}

{% block content %}
  <h1>Подтверждение сброса пароля</h1>
  {% include 'users/includes/base_users_template.html' %}
{% endblock %}

artina_apps/templates/users/password_reset_done.html
{% extends 'base.html' %}


{% block title %}
  Сброс пароля
{% endblock %}

{% block content %}
  <h1>Отмена пароля</h1>
  <div class="col-6 mx-auto">
    <p>Сообщение для отмены пароля отправлено</p>
    <p>Для смены пароля перейдите по ссылке, отправленной на почту</p>
    <p>Если что то пошло не так, напишите нам, перейдя на вкладку <span class="fw-bold">Обратная связь</span></p>
  </div>
{% endblock %}

artina_apps/templates/users/password_reset_mail.html
<div class='text-start'>
  <h3>Здравствуйте, {{ user }}</h3>
  <p>Ссылка перейдите по ссылке для сброса пароля ниже: {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}</p>
  <p>Если вы не запрашивали сброс пароля, напишите нам. С уважением от команды Artina</p>
</div>

artina_apps/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
  Профиль
{% endblock %}

{% block content %}
  <h1>Профиль</h1>
  {% load thumbnail %}
  {% thumbnail user.image "400x400" as image %}
    <img src="{{ image.url }}"
             width="{{ image.width }}"
             height="{{ image.height }}"
             class="rounded-circle z-depth-0"
             alt="Аватар">
  {% endthumbnail %}
  {% include 'users/includes/base_users_template.html' %}
{% endblock %}

artina_apps/templates/users/sign_up.html
{% extends 'base.html' %}

{% block title %}
  Регистрация
{% endblock %}

{% block content %}
  {% if request.user.is_authenticated %}
    <h1 class="mt-2">Вы уже вошли в аккаунт</h1>
  {% else %}
    <h1>Регистрация</h1>
    {% include 'users/includes/base_users_template.html' %}
  {% endif %}
{% endblock %}